service: visitor-management-backend

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  stage: dev
  environment:
    DYNAMODB_REGION: ${self:provider.region}
    VISITORS_TABLE: ${env:VISITORS_TABLE, 'visitors'}
    ADMINS_TABLE: ${env:ADMINS_TABLE, 'admins'}
    S3_BUCKET_NAME: ${env:S3_BUCKET_NAME, 'visitor-management-assets-dev'}
    JWT_SECRET: ${env:JWT_SECRET, 'supersecretkey123'}
    FRONTEND_URL: ${env:FRONTEND_URL, 'http://localhost:3000'}

functions:
  adminLogin:
    handler: dist/handlers/adminLogin.handler
    events:
      - http:
          path: auth/login
          method: post
          cors: true

  createVisitor:
    handler: dist/handlers/createVisitor.handler
    events:
      - http:
          path: visitors
          method: post
          cors: true

  getVisitors:
    handler: dist/handlers/getVisitors.handler
    events:
      - http:
          path: visitors
          method: get
          cors: true

  getVisitorById:
    handler: dist/handlers/getVisitorById.handler
    events:
      - http:
          path: visitors/{id}
          method: get
          cors: true

  checkoutVisitor:
    handler: dist/handlers/checkoutVisitor.handler
    events:
      - http:
          path: visitors/{id}/checkout
          method: patch
          cors: true

plugins:
  # If compiling TS dynamically at deploy time
  # - serverless-plugin-typescript
